### PR TITLE
updated pricing

### PR DESCRIPTION
**Pull request by ide-1**
The prices were fetched by means of going into sannes and taking a picture of the menu which means that it is not the same as the official online menu for sannes but hopefully it is accurate. 
I also added a disclaimer in the footer of the date when the prices were updated.

### CODE REVIEW

**Comment by ide-1** [comment]
also double-checked the ingredients and names of pizzas and fixed some

**Review by drakejacob — COMMENTED** [review]
Big effort, very nice

**Review by drakejacob — APPROVED** [review]
Big effort very nice but approve this time

**Review by x183 — APPROVED** [review]
Nice!

**Pull request merged**
